<?php

function CalculadoraCredito_block_info() {
  $blocks = array();
  $blocks['CalculadoraCredito_block'] = array(
    'info' => t('Calculadora'),
    );
  $blocks['CalculadoraCredito_view_modal'] = array(
    'info' => t('Calculadora Ventana'),
    );
    return $blocks;
}

function CalculadoraCredito_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'CalculadoraCredito_block':
    $block['subject'] = '';
    $block['content'] = CalculadoraCredito_block_content();
    break;

    case 'CalculadoraCredito_view_modal':
    $block['subjet'] ='';
    $block['content'] = modal_CalculadoraCredito_block_content();
    break;
  }
  return $block;
}

function CalculadoraCredito_block_content(){
  $module_path = drupal_get_path('module', 'CalculadoraCredito');
  drupal_add_js($module_path.'/js/calculadora.js');  
  drupal_add_js($module_path.'/js/jquery.number.js');  
  
  global $base_url;
  
  $readonly = '';
  $price    = '';
  $init     = '';
  $data     = '';

  $url = $base_url . '/sites/all/themes/at-vivendo/images/logos/logo-vivendo.png';
  $img = '<img class="logo-vivendo" src="'.$url.'" /><span style="color:#89878c">vivendo.</span style="color:#cd002d"><span>co</span>' ;
  
  if ( is_numeric(arg(1)) ) {
    $node = node_load( arg(1) );
    if ( $node->type == 'proyecto' ) {
      $price = $node->field_precio['und'][0]['value'];
      $init  = ($price * 0.30);
      $deuda = ($price - $init);
      
      $readonly = 'readonly="readonly"';
      
      $data = '<span class="text-respuesta"><strong>Precio:</strong> $'. number_format($price, 0, ',', '.') .'</span>
	       <span class="text-respuesta"><strong>Cuota inicial:</strong> $'. number_format($init, 0, ',', '.') .'</span>
	       <span class="text-respuesta"><strong>Valor a financiar:</strong> $'. number_format($deuda, 0, ',', '.') .'</span>';
      
      if ( !empty($node->field_patrocinador) ) {
	       $url = file_create_url($node->field_patrocinador['und'][0]['uri']);
	       $img = '<img src="'.$url.'" />';
      }
      
    }
  }
  
  $output = '<div class="contenedor">
                     <div class="block_calculadora">
                     <h2>CALCULE SU CR&Eacute;DITO</h2>
		     <div class="content-sponsor">'.$img.'</div>
                       <div id="mostrar_resultado">
                           <span class="text-respuesta" id="text-respuesta"></span><br><br>
                          <span class="respuesta" id="respuesta"></span>
                          <div class="boton_recal">
                          <button class="calcular_bn" onClick="recalcular()">VOLVER A CALCULAR</button>
                          </div>
                        </div>
                      <div id="items_calculadora">
                      <span>Diligencie el valor del prestamo a solicitar (70% del valor del inmueble)</span><br>
                      <input type="text" name="valor_compra" id="valor_compra" value="'.$price.'" '.$readonly.'/><br>
                      <div id="mensaje1" class="errores"> Ingresa solo números</div>
                      <span>Valor de cuota inicial (30% del valor del inmueble)</span><br>
                      <input type="text"/ name="valor_inicial" id="valor_inicial" value="'.$init.'"><br>
                      <div id="mensaje2" class="errores"> Ingresa un valor mayor </div>
                      <div class="select_calcular"><span>Tasa</span><br>
                        <select name="tasa" id="tasa" >
                          <option value="0.890">11,22% E.A</option>
                        </select><br>
                      </div>

                      <div class="select_calcular periodos"  > <span>Periodos<span><br>
                        <select name="periodos" id="periodos" >
                          <option value="120">120 Meses</option>
                          <option value="180"selected="selected">180 Meses</option>
                          <option value="240">240 Meses</option>
                        </select><br>
                        </div>
			<div class="content-default">'.$data.'</div>
      <div  class="content-default">
			  <span class="text-respuesta">*Modalidad cuota fija en pesos.</span>
        <span class="text-respuesta"><br/><strong>*Nota:</strong> 
las cifras mostradas aquí son una aproximación ESTE VALOR NO INCLUYE SEGUROS 
El porcentaje de financiación de crédito varía dependiendo las políticas de cada constructora.<br/></span></div>
<div  class="content-default">
<span class="text-respuesta">*Fuente: Superintendencia bancaria</span>
</div>
                        <div>
                          <button name="calcular_bn" id="calcular_bn" class="calcular_bn" onClick="calcular()"><span class="text-boton">CALCULAR</span>
                          </button>
                        </div>
                     </div>
                    <div>
             </div>
          </div>
        </div>
       ';
  return $output;
}
function modal_CalculadoraCredito_block_content(){
  $module_path = drupal_get_path('module', 'CalculadoraCredito');
  drupal_add_js($module_path.'/js/calculadora.js');  
  drupal_add_js($module_path.'/js/jquery.number.js');  
  
  global $base_url;
  
  $readonly = '';
  $price    = '';
  $init     = '';
  $data     = '';

  $url = $base_url . '/sites/all/themes/at-vivendo/images/logos/logo-vivendo.png';
  $img = '<img class="logo-vivendo" src="'.$url.'" /><span style="color:#89878c">vivendo.</span style="color:#cd002d"><span>co</span>' ;
  
  if ( is_numeric(arg(1)) ) {
    $node = node_load( arg(1) );
    if ( $node->type == 'proyecto' ) {
      $price = $node->field_precio['und'][0]['value'];
      $init  = ($price * 0.30);
      $deuda = ($price - $init);
      
      $readonly = 'readonly="readonly"';
      
      $data = '<span class="text-respuesta"><strong>Precio:</strong> $'. number_format($price, 0, ',', '.') .'</span>
         <span class="text-respuesta"><strong>Cuota inicial:</strong> $'. number_format($init, 0, ',', '.') .'</span>
         <span class="text-respuesta"><strong>Valor a financiar:</strong> $'. number_format($deuda, 0, ',', '.') .'</span>';
      
      if ( !empty($node->field_patrocinador) ) {
         $url = file_create_url($node->field_patrocinador['und'][0]['uri']);
         $img = '<img src="'.$url.'" />';
      }
      
    }
  }
  
  $output = '<div class="contenedor">
                     <div class="block_calculadora">
                     <h2>CALCULE SU CR&Eacute;DITO</h2>
         <div class="content-sponsor">'.$img.'</div>
                       <div id="mostrar_resultado">
                           <span class="text-respuesta" id="text-respuesta"></span><br><br>
                          <span class="respuesta" id="respuesta"></span>
                          <div class="boton_recal">
                          <button class="calcular_bn" onClick="recalcular()">VOLVER A CALCULAR</button>
                          </div>
                        </div>
                      <div id="items_calculadora">
                      <span>Diligencie el valor del prestamo a solicitar (70% del valor del inmueble)</span><br>
                      <input type="text" name="valor_compra" id="valor_compra" value="'.$price.'" '.$readonly.'/><br>
                      <div id="mensaje1" class="errores"> Ingresa solo números</div>
                      <span>Valor de cuota inicial (30% del valor del inmueble)</span><br>
                      <input type="text"/ name="valor_inicial" id="valor_inicial" value="'.$init.'"><br>
                      <div id="mensaje2" class="errores"> Ingresa un valor mayor </div>
                      <div class="select_calcular"><span>Tasa</span><br>
                        <select name="tasa" id="tasa" >
                          <option value="0.890">11,22% E.A</option>
                        </select><br>
                      </div>

                      <div class="select_calcular periodos"  > <span>Periodos<span><br>
                        <select name="periodos" id="periodos" >
                          <option value="120">120 Meses</option>
                          <option value="180"selected="selected">180 Meses</option>
                          <option value="240">240 Meses</option>
                        </select><br>
                        </div>
      <div class="content-default">'.$data.'</div>
        <div  class="content-default">
        <span class="text-respuesta">*Modalidad cuota fija en pesos.</span>
        <span class="text-respuesta"><br/><strong>*Nota:</strong> 
las cifras mostradas aquí son una aproximación ESTE VALOR NO INCLUYE SEGUROS 
El porcentaje de financiación de crédito varía dependiendo las políticas de cada constructora.<br/></span></div>
<div  class="content-default">
<span class="text-respuesta">*Fuente: Superintendencia bancaria</span>
</div>
                        <div>
                          <button name="calcular_bn" id="calcular_bn" class="calcular_bn" onClick="calcular()"><span class="text-boton">CALCULAR</span>
                          </button>
                        </div>
                     </div>
                    <div>
             </div>
          </div>
        </div>
       ';
  return $output;
}
