<?php
  
  function vivendo_send_mail_menu() {
  
    $items = array();

    $items['send-mail-contruct'] = array(
        'access arguments'  => array( 'access content' ),
        'page arguments'    => array(),
        'page callback'     => 'vivendo_send_mail_callback',
        'title'             => t('Send Link'),
        'type'              => MENU_CALLBACK
    );

    return $items;

  }


  function vivendo_send_mail_callback(){

    if(isset($_REQUEST['name'])){
    
      $dataSend                = $_REQUEST;
      $contactConstruct        = entity_create( 'entityform', array('type' =>'contacto_contructores') );
      $contactConstructWrapper = entity_metadata_wrapper( 'entityform', $contactConstruct );

      $contactConstructWrapper->created               = time();
      $contactConstructWrapper->changed               = time();
      $contactConstructWrapper->field_nombre          = $dataSend['name'];
      $contactConstructWrapper->field_apellidos       = $dataSend['lastName'];
      $contactConstructWrapper->field_email           = $dataSend['email'];
      $contactConstructWrapper->field_telefono1       = $dataSend['telephone'];
      $contactConstructWrapper->field_pais            = $dataSend['country'];
      $contactConstructWrapper->field_ciudad_contact  = $dataSend['city'];
      $contactConstructWrapper->field_project_name    = $dataSend['project'];
      $contactConstructWrapper->field_contructor_name = $dataSend['construct'];
      

      $contactConstructWrapper->save();
    
    }

    return '<div>1</div>';

  }