<?php

  function vivendo_telephone_click_menu() {
    
    $items = array();
    
    $items['vivendo-telephone/%'] = array(
        'access arguments' => array( 'access content' ),
        'page arguments'   => array( 1 ),
        'page callback'    => 'vivendo_telephone_click_callback',
        'title'            => t('Telephone click'),
        'type'             => MENU_CALLBACK,
    );
    
    return $items;
    
  }
  
  
  
  function vivendo_telephone_click_callback( $eid ){
    
    $result = db_insert( 'vivendo_telephone' )
        ->fields(array(
            'created'   => REQUEST_TIME,
            'bundle'    => 'contructora',
            'entity_id' => $eid
        ))
        ->execute();
    
    ajax_deliver( array('#type' => 'ajax', '#commands' => array()) );
    
  }
  
  
  
  function vivendo_telephone_click_views_api() {
    
    return array(
        'api'  => 3,
        'path' => drupal_get_path( 'module',  'vivendo_telephone_click' )
    );
    
  }
  
  
  function vivendo_telephone_click_form_alter(&$form, &$form_state, $form_id){
    
    if ( $form_id == 'contacto_contructores_entityform_edit_form' ){
      
      $node = node_load( arg(1) );
      
      if(is_object($node)){
        
        dpm( $node );
        
        
        $form['field_project_name']['#attributes']['style']    = 'display: none;';
        $form['field_contructor_name']['#attributes']['style'] = 'display: none;';
        $form['field_email_send']['#attributes']['style']      = 'display: none;';

        $form['field_project_name']['und'][0]['value']['#default_value']    = $node->title;
        $form['field_contructor_name']['und'][0]['value']['#default_value'] = $node->field_constructora['und'][0]['entity']->title;
        $form['field_email_send']['und'][0]['value']['#default_value']      = 'ftorres@dayscript.com';//$node->field_constructora['und'][0]['entity']->field_email['und'][0]['email'];
        
        $form['field_ley_1581']['und']['#default_value'] = NULL;
        
      }
      
    }
    
  }