<?php

	function vivendo_filter_views_api() {
		
		return array(
			'api' => 3,
			'path' => drupal_get_path( 'module',  'vivendo_filter' )
		);

	}

	function vivendo_filter_form_alter( &$form, &$form_state, $form_id ) {

		if ( $form_id == 'simplenews_block_form_310' ) {

			$form['content'] = array(
				'#prefix' => '<div id="content-field-simplenews">',
				'#suffix' => '</div>'
			);

			$form['content'][] = $form['mail'];

			$form['content']['ley'] = array(
				'#type'     => 'checkbox',
				'#title'    => 'Acepto y autorizo de conformidad la Ley <a href="http://newvivendo.dayscript.com/terminos-y-condiciones">1581 de 2012</a>',
				'#required' => TRUE
			);

			unset( $form['mail'] );
		}

	}