<?php
/**
 * @file
 * A block module that displays a modal window to select global filter value
 */


/*function global_filter_selector_menu(){

  $items = array();
  
  $items['region/%'] = array(
      'access arguments'  => array( 'access content' ),
      'page arguments'    => array(1),
      'page callback'     => 'global_filter_selector_change_filter',
      'title'             => t('Search link'),
      'type'              => MENU_CALLBACK
  );
  
  return $items;
  
}*/

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function global_filter_selector_help($path, $arg) {
  switch ($path) {
    case "admin/help#global_filter_selector":
      return '<p>' . t("Displays a modal window to select filter value.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function global_filter_selector_block_info() {
  $blocks['global_filter_selector'] = array(
    // The name that will appear in the block list.
    'info' => t('Selector de ciudad'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Custom function.
 *
 * Checks the Global Filter Session Variable
 *
 * @return
 *   If the global filter value is set
 */
function global_filter_selector_status(){
//  print_r($_SESSION);
  $value = global_filter_get_session_value('field_region');
  if(is_array($value) && isset($value[0]))
    return true;
  else
    return false;
}

/**
 * Implements hook_block_view().
 */
function global_filter_selector_block_view($delta = '') {
  switch ($delta) {
    case 'global_filter_selector':
      $block['subject'] = t('Selector de ciudad');
      if (user_access('access content')) {
        if(global_filter_selector_status()){
          $items[] = array('data' => l("Clear", '',array('query'=>array("clear-global-filters"=>"field_region"))));
        } else{
            drupal_add_js('
              jQuery(document).ready(function(){
                jQuery.colorbox({inline:true, href:"#city_selector",overlayClose:false,escKey:false, closeButton:false, iframe:false});
              });','inline');

          $items[] = array('data' => l("Bogotá región centro", null,array('attributes'=>array('class'=>array('bogota')),'query'=>array("field_ciudad"=>"1"))));
          $items[] = array('data' => l("Cali Valle", null,array('attributes'=>array('class'=>array('cali')),'query'=>array("field_ciudad"=>"2"))));
          $items[] = array('data' => l("Medellín Antioquia", null,array('attributes'=>array('class'=>array('medellin', 'disabled')))));
          $items[] = array('data' => l("Eje Cafetero", null,array('attributes'=>array('class'=>array('ejecafetero', 'disabled')))));
          $items[] = array('data' => l("Santanderes", null,array('attributes'=>array('class'=>array('santanderes', 'disabled')))));
          $items[] = array('data' => l("Costa Atlántica", null,array('attributes'=>array('class'=>array('costa', 'disabled')))));
          $items[] = array('data' => l("La Florida", null,array('attributes'=>array('class'=>array('florida', 'disabled')))));
        }
          $block['content'] = global_filter_selector_callback_block();
      }
      return $block;
   }
}


function global_filter_selector_callback_block(){

  $output = '';

  $regiones = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('regiones')->vid);
  
  $output .= '<div id="city_selector">';
  $output .=   '<div class="logo">';
  $output .=     '<img alt="Vivendo.co" src="/sites/all/themes/at-vivendo/images/logos/logo-vivendo.png"/>';
  $output .=     '<span style="color:#89878c">vivendo.</span>';
  $output .=     '<span style="color:#cd002d">co</span>';
  $output .=   '</div>';
  $output .=   '<div class="intro">';
  $output .=     '<span class="text-intro">' . t('Encuentre aquí la más completa oferta de vivienda, casas y apartamentos en Colombia y Florida EEUU.') . '</span>';
  $output .=   '</div>';
  $output .=   '<div class="item-list"><ul>';
  
  foreach( $regiones as $region ){
    
    $regionDataComplete = taxonomy_term_load($region->tid);
    
    if ( $regionDataComplete->field_estado_region['und'][0]['value'] == 'activo' ){
      $name   = '<span>'.$regionDataComplete->name.'</span>';
      $aliasPath = drupal_get_path_alias('taxonomy/term/'.$regionDataComplete->tid);
      $action = 'href="?field_region='.$regionDataComplete->tid.'"';
    } else{
      $name   = '<span class="text-disabled"><strong>Próximamente</strong><br>'.$regionDataComplete->name.'</span>';
      $action = 'class="disabled"';
    }
    
    $output .=     '<li>';
    $output .=       '<a '.$action.'>';
    $output .=         '<img src="'.image_style_url('images_region_94x94', $regionDataComplete->field_image['und'][0]['uri']).'" alt="'.$regionDataComplete->name.'" title="'.$regionDataComplete->name.'" />';
    $output .=         $name;
    $output .=       '</a>';
    $output .=     '</li>';
  }
  
  $output .=   '</ul></div>';
  $output .= '</div>';

  return $output;

}


/*function global_filter_selector_change_filter($urlRegion){
  
  $urlTerm = explode( '/', drupal_get_normal_path($urlRegion) );
  $region  = array( $urlTerm[2] );
  
  global_filter_set_on_session('field_region', $region);

  drupal_goto('/');
  
}*/
