<?php
/**
 * @file
 * A block module that displays a modal window to select global filter value
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function global_filter_selector_help($path, $arg) {
  switch ($path) {
    case "admin/help#global_filter_selector":
      return '<p>' . t("Displays a modal window to select filter value.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function global_filter_selector_block_info() {
  $blocks['global_filter_selector'] = array(
    // The name that will appear in the block list.
    'info' => t('Selector de ciudad'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Custom function. 
 * 
 * Checks the Global Filter Session Variable
 * 
 * @return 
 *   If the global filter value is set
 */
function global_filter_selector_status(){
//  print_r($_SESSION);
  $value = global_filter_get_session_value('field_ciudad');
  if(is_array($value) && isset($value[0]))
    return true;
  else
    return false;
}

/**
 * Implements hook_block_view().
 */
function global_filter_selector_block_view($delta = '') {
  switch ($delta) {
    case 'global_filter_selector':
      $block['subject'] = t('Selector de ciudad');
      if (user_access('access content')) {
        if(global_filter_selector_status()){
          $items[] = array('data' => l("Clear", '',array('query'=>array("clear-global-filters"=>"field_ciudad"))));
        } else{
            drupal_add_js('
              jQuery(document).ready(function(){
                jQuery.colorbox({inline:true, href:"#city_selector",overlayClose:false,escKey:false, closeButton:false, iframe:false});
              });','inline');

          $items[] = array('data' => l("Bogotá Cundinamarca", null,array('attributes'=>array('class'=>array('bogota')),'query'=>array("field_ciudad"=>"1"))));
          $items[] = array('data' => l("Cali Valle", null,array('attributes'=>array('class'=>array('cali')),'query'=>array("field_ciudad"=>"2"))));
          $items[] = array('data' => l("Medellín Antioquia", null,array('attributes'=>array('class'=>array('medellin', 'disabled')))));
          $items[] = array('data' => l("Eje Cafetero", null,array('attributes'=>array('class'=>array('ejecafetero', 'disabled')))));
          $items[] = array('data' => l("Santanderes", null,array('attributes'=>array('class'=>array('santanderes', 'disabled')))));
          $items[] = array('data' => l("Costa Atlántica", null,array('attributes'=>array('class'=>array('costa', 'disabled')))));
        }
        $block['content'] = theme('item_list', array('items' => $items));
        $block['content'] = "<div class='logo'><img alt='Vivendo.co' src='/sites/all/themes/at-vivendo/images/logos/logo-vivendo.png' 
                              style='border-style:solid; border-width:0px; height:62px; width:71px'><span style='color:#89878c'>vivendo.</span>
                              <span style='color:#cd002d'>co</span></div>". $block['content'];
        $block['content'] = "<div class='intro'>Encuentre aquí la más completa oferta de vivenda, casas y apartamentos en Colombia</div>" . $block['content'];
        $block['content'] = "<div id='city_selector'>" . $block['content'] . "</div>";
      }
      return $block;
   } 
}