<?php


  function vivendo_reports_menu(){
    
    $items = array();
  
    $items['admin/report/projects'] = array(
        'access arguments'  => array( 'access content' ),
        'page arguments'    => array(),
        'page callback'     => 'vivendo_reports_project_callback',
        'title'             => t('Reporte proyectos'),
        'type'              => MENU_CALLBACK
    );

    return $items;
    
  }
  
  
  function vivendo_reports_project_callback(){
    
    $result = _query_list_project();
    $table  = array();
    $output = '';
    
    $table['header'] = array(
        array('data' => t('Codigo'), 'field' => 'field_data_field_codigo_value', 'sort' => 'ASC'),
        array('data' => t('Projecto'), 'field' => 'node_title', 'sort' => 'ASC'),
        array('data' => t('Email'), 'field' => 'field_data_field_email_node_entity_type', 'sort' => 'ASC'),
        array('data' => t('Región'), 'field' => 'region_name', 'sort' => 'ASC'),
        array('data' => t('Ciudad'), 'field' => 'city_name', 'sort' => 'ASC'),
        array('data' => t('Zona'), 'field' => 'zone_name', 'sort' => 'ASC'),
        array('data' => t('Constructora'), 'field' => 'construct_name', 'sort' => 'ASC'),
        array('data' => t('Estado'), 'field' => 'node_status', 'sort' => 'ASC'),
        array('data' => t('Fecha de creación'), 'field' => 'node_created', 'sort' => 'ASC'),
    );
    
    for( $i=0; $i<count($result); $i++ ){
      
      $table['rows'] = array(
          array( 'data' => $result[$i]->field_data_field_codigo_value ),
          array( 'data' => $result[$i]->node_title ),
          array( 'data' => $result[$i]->field_data_field_email_node_entity_type ),
          array( 'data' => $result[$i]->region_name ),
          array( 'data' => $result[$i]->city_name ),
          array( 'data' => $result[$i]->zone_name ),
          array( 'data' => $result[$i]->construct_name ),
          array( 'data' => $result[$i]->node_status ),
          array( 'data' => $result[$i]->node.created ),
      );
      
    }
    
    $output .= theme('table', $table);
    $output .= theme('pager');
    
    return $output;
    
  }
  
  
  function _query_list_project(){
    
    $sql = "SELECT node.nid AS nid,
        node.title AS node_title,
        node.status AS node_status,
        node.created AS node_created,
        field_codigo.field_codigo_value AS field_data_field_codigo_value,
        field_email.field_email_email AS field_data_field_email_node_entity_type,

          (SELECT node.title
           FROM node
           WHERE node.nid = field_constructora.field_constructora_target_id) AS construct_name,

          (SELECT taxonomy_term_data.name AS rname
           FROM taxonomy_term_data
           WHERE taxonomy_term_data.tid = field_region.field_region_tid) AS region_name,

          (SELECT taxonomy_term_data.name AS cname
           FROM taxonomy_term_data
           WHERE taxonomy_term_data.tid = field_ciudad.field_ciudad_tid) AS city_name,

          (SELECT taxonomy_term_data.name AS zname
           FROM taxonomy_term_data
           WHERE taxonomy_term_data.tid = field_zona.field_zona_tid) AS zone_name
        FROM node
        LEFT JOIN field_data_field_codigo AS field_codigo ON node.nid = field_codigo.entity_id
        LEFT JOIN field_data_field_region AS field_region ON node.nid = field_region.entity_id
        LEFT JOIN field_data_field_ciudad AS field_ciudad ON node.nid = field_ciudad.entity_id
        LEFT JOIN field_data_field_zona AS field_zona ON node.nid = field_zona.entity_id
        LEFT JOIN field_data_field_email AS field_email ON node.nid = field_email.entity_id
        LEFT JOIN field_data_field_constructora AS field_constructora ON node.nid = field_constructora.entity_id
        WHERE node.type = 'proyecto'
        ORDER BY node_created DESC LIMIT 60
        OFFSET 0";
    
    $query  = db_query( $sql );
    $result = $query->fetchAll();
    
    return $result;
    
  }
  
  
  
