<?php


  function vivendo_pdf_export_menu() {
    
    $items = array();

    $items['exportar-proyecto/%'] = array(
        'access arguments' => array( 'access content' ),
        'page arguments'   => array( 1 ),
        'page callback'    => 'vivendo_pdf_export_callback',
        'title'            => t('Exportar proyecto'),
        'type'             => MENU_CALLBACK,
    );

    return $items;
    
  }
  
  
  
  function vivendo_pdf_export_callback( $nId ) {
    
    $projectWrapper = entity_metadata_wrapper( 'node', $nId );
    
    $varLogoProject = array(
        'style_name' => 'escalar_289x66-copy',
        'path'       => $projectWrapper->field_image->value()['uri'],
        'width'      => $projectWrapper->field_image->value()['width'],
        'height'     => $projectWrapper->field_image->value()['height'],
        'alt'        => $projectWrapper->field_image->value()['alt'],
        'title'      => $projectWrapper->field_image->value()['title']
    );
    
    $varLogoConstruct = array(
        'style_name' => 'escalar_289x66-copy',
        'path'       => $projectWrapper->field_constructora->value()->field_image['und'][0]['uri'],
        'width'      => $projectWrapper->field_constructora->value()->field_image['und'][0]['width'],
        'height'     => $projectWrapper->field_constructora->value()->field_image['und'][0]['height'],
        'alt'        => $projectWrapper->field_constructora->value()->field_image['und'][0]['alt'],
        'title'      => $projectWrapper->field_constructora->value()->field_image['und'][0]['title'],
    );
    
    $varImageProject = array(
        'style_name' => 'escalar_a_846x489',
        'path'       => $projectWrapper->field_fotos->value()[0]['uri'],
        'width'      => $projectWrapper->field_fotos->value()[0]['width'],
        'height'     => $projectWrapper->field_fotos->value()[0]['height'],
        'alt'        => $projectWrapper->field_fotos->value()[0]['alt'],
        'title'      => $projectWrapper->field_fotos->value()[0]['title'],
    );
    
    $featuresIn  = $projectWrapper->field_interiores->value();
    $featuresOff = $projectWrapper->field_exteriores->value();
    
    $output = '';
    
    $output .= '
      <style>
      #main-info-project {
    overflow: hidden;
    margin-bottom: 8px;
}

.columns {
    float: left;
    overflow: hidden;
}

#main-info-project .columns {
    padding-right: 15px;
    border-right: 2px solid #cccccc;
    margin-right: 15px;
    float: left;
    width: 300px;
}

#main-info-project .columns .content-logo-project {
    float: left;
    width: 120px;
    height: 72px;
}

.address {
  font-size: 13px;
  padding-left: 10px;
  padding-top: 5px;
  width: 300px;
}

.content-logo-project {
    float: left;
}

.info {
    float: left;
}

.info span {
    display: block;
}

.address {
    clear: both;
}

.main-image {
    position: relative;
    display: table;
}

.content-image {
    position: absolute;
    top: 0;
    left: 0;
}

.content-price {
    position: absolute;
    top: 33px;
    right: 0;
    background: #c80016;
    padding: 12px 38px;
    color: #fff;
    font-size: 30px;
    width: 190px;
    margin-left: 420px;
    margin-top: 15px;
}

.main-image {
  background-image: url("'.image_style_url('escalar_a_846x489', $projectWrapper->field_fotos->value()[0]['uri']).'");
  background-repeat: no-repeat;
    width: 846px;
    height: 489px;
    
}

h2 {
    color: #666666;
    text-transform: uppercase;
    font-weight: 600;
    font-size: 18px;
}

.page-exportar-proyecto #content-wrapper {
    width: 865px;
}

.page-exportar-proyecto #page-title {
    display: none;
}

.description {
    width: 170px;
    padding-left: 30px;
}

.features-off {
    display: block;
    margin-bottom: 50px;
}

.item {
    display: block;
    float: left;
    width: 175px; 
}

.content-general .columns{
  width: 350px;
  float: left;
}

</style>';
    
    $output .= '<div class="group-info">';
    $output .=   '<div id="main-info-project">';
    
    $output .=     '<div class="columns">';
    $output .=       '<div class="content-logo-project">';
    $output .=         theme_image_style( $varLogoProject );
    $output .=       '</div>';
    $output .=       '<div class="info">';
    $output .=         '<h2>' . $projectWrapper->title->value() . '</h2>';
    $output .=         '<div class="type">' . $projectWrapper->field_tipo->value()->name . '</div>';
    $output .=         '<div class="zone">' . $projectWrapper->field_zona->value()->name . '</div>';
    $output .=       '</div>';
    $output .=       '<div class="address">' . $projectWrapper->field_direccion->value() . '</div>';
    $output .=     '</div>';
    
    $output .=     '<div clas="columns">';
    $output .=       '<div class="content-logo-contruct">';
    $output .=         theme_image_style( $varLogoConstruct );
    $output .=       '</div>';
    $output .=     '</div>';
    
    $output .=   '</div>';
    
    $output .=   '<div class="main-image">';
    /*$output .=     '<div class="content-image">';
    $output .=       theme_image_style( $varImageProject );
    $output .=     '</div>';*/
    $output .=     '<div class="content-price">';
    $output .=       '<span> Desde: ' . is_numeric($projectWrapper->field_precio->value()) ? '$' . number_format($projectWrapper->field_precio->value(), 0, ',', '.') : 'No Disponible' . ' </span>';
    $output .=     '</div>';
    $output .=   '</div>';
    
    $output .=   '<div class="general-info">';
    $output .=     '<div class="features">';
    $output .=       '<h1>Especificaciones</h1>';
    $output .=       '<div class="features-in">';
    
    if ( !empty($featuresIn) ):
    $output .=         '<h2>Características Interiores</h2>';
    $output .=         '<div class="items">';
    for ( $i=0; $i<count($featuresIn); $i++ ):
    $output .=           '<div class="item">' . $featuresIn[$i]->name . '</div>';
    endfor;
    $output .=         '</div>';
    endif;
    
    $output .=       '</div>';
    $output .=       '<div class="features-off">';
    
    if ( !empty($featuresOff) ):
    $output .=         '<h2>Características Interiores</h2>';
    $output .=         '<div class="items">';
    for ( $i=0; $i<count($featuresOff); $i++ ):
    $output .=           '<div class="item">' . $featuresOff[$i]->name . '</div>';
    endfor;
    $output .=         '</div>';
    endif;
    
    $output .=       '</div>';
    $output .=     '</div>';
    $output .=     '<div class="content-general">';
    $output .=       '<div class="columns">';
    $output .=         '<table>';
    $output .=           '<tr>';
    $output .=             '<td>Ciudad:</td>';
    $output .=             '<td>' . $projectWrapper->field_ciudad->value()->name . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Barrio:</td>';
    $output .=             '<td>' . $projectWrapper->field_barrio->value()->name . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Estrato:</td>';
    $output .=             '<td>' . $projectWrapper->field_estrato->value()->name . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Alcobas:</td>';
    $output .=             '<td>' . $projectWrapper->field_alcobas->value() . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Baños:</td>';
    $output .=             '<td>' . $projectWrapper->field_banos->value() . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Area construida desde: </td>';
    $output .=             '<td>' . $projectWrapper->field_area_construida->value() . '</td>';
    $output .=           '</tr>';
    $output .=           '<tr>';
    $output .=             '<td>Area privada desde: </td>';
    $output .=             '<td>' . $projectWrapper->field_area_privada->value() . '</td>';
    $output .=           '</tr>';
    $output .=         '</table>';
    $output .=       '</div>';
    $output .=       '<div class="columns">';
    $output .=         '<div class="description">';
    $output .=           '<h1>Descripción</h1>';
    $output .=           '<div class="content">' . $projectWrapper->body->value()['value'] . '</div>';
    $output .=         '</div>';
    $output .=       '</div>';
    $output .=     '</div>';
    $output .=   '</div>';
    $output .= '</div>';
    
    include('libraries/MPDF56/mpdf.php');
    
    $mpdf = new mPDF('utf-8', 'Letter');
    
    $mpdf->SetDisplayMode('fullpage');
    
    $mpdf->WriteHTML( $output );
    $mpdf->Output();
    
    exit;
    //return $output;
    
  }

